# Generated by Django 3.1.6 on 2021-04-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210410_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
