# Generated by Django 3.1.6 on 2021-04-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210412_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='facebook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='instagram',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
