# Generated by Django 3.1.6 on 2021-04-24 14:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210419_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_comment',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
